### ISSUE TITLE
[Bug] Auth information should not be printed to STDOUT

### ISSUE THREAD

**Issue by jkirkham-ratehub** [mgmonteleone/python-atlasapi#21]
I have an application using this module and output is aggregated to LogDNA.  Many more people can see the log output than the small number who should have access to the Mongo Atlas API keys.

This line:
https://github.com/mgmonteleone/python-atlasapi/blob/dea498f7230869c2502d5990ffee02ca947abdff/atlasapi/network.py#L102
is printing to STDOUT.
This could be useful, but I think it would be better to keep this by only logging it on DEBUG level so it does not show up in more public logs.

**Comment by mgmonteleone** [comment]
Thanks @jkirkham-ratehub , I will put take care of this in the next cycle.

Will expand this a bit to remove all print statements, and either move to log or remove completely.
