### ISSUE TITLE
Projects unavailable 

### ISSUE THREAD

**Issue by derklauer-ocean** [mgmonteleone/python-atlasapi#35]
Possible bug following documentation to get projects.

```
from atlasapi.atlas import Atlas

a = Atlas("U","P","GID")

# Get All Projects
for project in a.Projects.get_all_projects(iterable=True):
    print(project["name"])

```

Returns:

```
AttributeError                            Traceback (most recent call last)
<ipython-input-1-e148b584ba06> in <module>
      4 
      5 # Get All Projects
----> 6 for project in a.Projects.get_all_projects(iterable=True):
      7     print(project["name"])

AttributeError: 'Atlas' object has no attribute 'Projects'
```

**Comment by mgmonteleone** [comment]
Thanks @derklauer-ocean , I will look into this during this week.

**Comment by mgmonteleone** [comment]
@derklauer-ocean 
Yes, for now this endpoint is not implemented, the API is currently scoped to work with one Project/Group.

If enabling the bindings to work at the Organization level is important, please let me know, and I can look at adding that functionality. 

For now I am removing reference to this in the README
