### ISSUE TITLE
Get All Clusters of All projects (Regardless of the group id)

### ISSUE THREAD

**Issue by slopez-lmes** [mgmonteleone/python-atlasapi#84]
Hi, 

Having this feature would be amazing, because right now you can access all clusters of a project (group_id), but not of all your projects (easily). The endpoint in Mongo: https://www.mongodb.com/docs/atlas/reference/api/clusters-get-all-key/ 

Regards

**Comment by mgmonteleone** [comment]
Thanks @slopez-lmes , I will look into this!

**Comment by mgmonteleone** [comment]
@slopez-lmes , looking to implement this directly in v2.1.X in the next week or so.

**Comment by mgmonteleone** [comment]
Moved this to v3.0, working on it now.

**Comment by mgmonteleone** [comment]
@macintacos , since this is a new endpoint, going to experiment with using OpenAPI and Pydantic as you suggested.

**Comment by mgmonteleone** [comment]
Created backport issue #141 , going to close this one out , since this is completed in 3.0, which should be released in the next 2 weeks.
