### ISSUE TITLE
Support for Database level Metrics

### ISSUE THREAD

**Issue by ghost** [mgmonteleone/python-atlasapi#92]
Thanks so much for building this library, it is super helpful!

Is there any support yet for database level metric retrieval ([these](https://www.mongodb.com/docs/atlas/reference/api/process-databases-measurements/#measurement-values) specifically)?

DATABASE_AVERAGE_OBJECT_SIZE
DATABASE_COLLECTION_COUNT
DATABASE_DATA_SIZE
DATABASE_STORAGE_SIZE
DATABASE_INDEX_SIZE
DATABASE_INDEX_COUNT
DATABASE_EXTENT_COUNT
DATABASE_OBJECT_COUNT
DATABASE_VIEW_COUNT

I've been looking through the source and documentation but haven't been able to find anything close to it other than the host level metrics.

-------------

Two Components:

- [x]  Get all databases
- [x] Get metrics for database

**Comment by mgmonteleone** [comment]
Thanks @luffespresso for submitting this! 

Indeed, this has not yet been implemented. I will look into implementing this soon, and will update on this issue once work begins.

**Comment by mgmonteleone** [comment]
Scheduled for measurements v2 release next week.

**Comment by mgmonteleone** [comment]
Now targeting Release 2022-06-23

**Comment by mgmonteleone** [comment]
Adding both:

**https://www.mongodb.com/docs/atlas/reference/api/process-databases/** (get all databases)
and
**https://www.mongodb.com/docs/atlas/reference/api/process-databases-measurements/** (get measurements for database)

**Comment by mgmonteleone** [comment]
Completed! @luffespresso will tag you for review.

**Comment by mgmonteleone** [comment]
PR is now ready (#113), @luffespresso , please let me know if you would like to be a reviewer.

**Comment by mgmonteleone** [comment]
Will mark this as closed, as we are only awaiting the PR to complete for release.

This is available in 2.0.rc1 if you want to use that version on pypi before the PR is completed.
